### ISSUE TITLE
elect a best slave for promotion?

### ISSUE THREAD

**Issue by siddontang** [ngaut/codis-ha#1]
```
func getSlave(master *models.Server) (*models.Server, error) {
    var group models.ServerGroup
    err := callHttp(&group, genUrl(*apiServer, "/api/server_group/", master.GroupId), "GET", nil)
    if err != nil {
        return nil, errors.Trace(err)
    }

    for _, s := range group.Servers {
        if s.Type == models.SERVER_TYPE_SLAVE {
            return &s, nil
        }
    }

    return nil, errors.Errorf("can not find any slave in this group: %v", group)
}
```

If the master has more slaves, we must choose the best one which has the most up-to-date data with master, not just the first one.

I think we can use [Role](http://redis.io/commands/role) command to get the slave's replication offset, and elect the best one which has the biggest offset.

**Comment by ngaut** [comment]
you are right, this is a simple strategy. there is always only one slave :)
